version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: erp_postgres
    restart: always
    environment:
      POSTGRES_USER: erpfallen
      POSTGRES_PASSWORD: erpfallen
      POSTGRES_DB: erpdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
